In [4]:
!python -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
a = np.array([[3,8,4] , [9,3,5] , [11,15,17] , [19,31,8]])
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [8]:
b = np.array([[[4,41],[8,81],[7,71]] , 
              [[3,31],[1,11],[5,51]] , 
              [[6,61],[9,91],[13,131]]])
b

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [9]:
b.shape

(3, 3, 2)

In [10]:
a[0,1] #subscripting


8

In [11]:
a[0][1] #indexing

8

In [12]:
a[0,0:3:1]
a[0,:] #slicing  #short

array([3, 8, 4])

In [21]:
# a[0:5:1,2:3]
# a[:,2].shape #short
a[:,-1:3:1]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [26]:
b[1:,1:,:1]
# b[1:3:1,1:3:1,0]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [ ]:
# find 3,6,31,61


In [27]:
a +5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [31]:
a[0] = 13
a

array([[13, 13, 13],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [32]:
a

array([[13, 13, 13],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [33]:
a = np.array([[3,8,4] , [9,3,5] , [11,15,17] , [19,31,8]])

In [34]:
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [35]:
a[0,:] = [30,40,50]
a

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [36]:
a[:,1] = [60,70,80,90]
a

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17],
       [19, 90,  8]])

In [ ]:
# a[1:,:1] = [[202,404], [303,505]]

In [40]:
np.append(a,[[1,1,1]],axis = 0) #zero to add row-wise

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17],
       [19, 90,  8],
       [ 1,  1,  1]])

In [41]:
np.append(a,[[1],[1],[1],[1]],axis = 1) #one to add column-wise

array([[30, 60, 50,  1],
       [ 9, 70,  5,  1],
       [11, 80, 17,  1],
       [19, 90,  8,  1]])

In [42]:
np.delete(a,1,0)

array([[30, 60, 50],
       [11, 80, 17],
       [19, 90,  8]])

In [44]:
np.delete(a,1,1)

array([[30, 50],
       [ 9,  5],
       [11, 17],
       [19,  8]])

In [46]:
np.delete(a,3,axis=0)

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17]])

In [48]:
a

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17],
       [19, 90,  8]])

In [49]:
a.reshape(6,2)

array([[30, 60],
       [50,  9],
       [70,  5],
       [11, 80],
       [17, 19],
       [90,  8]])

In [50]:
a.dtype

dtype('int32')

In [ ]:
a1 = np

In [ ]:
# Nutshell
## we create arrays
# 1.np.array()
# 2.np.ones()
# 3.np.zeros()
# 4.np.arange()
# 5.np.linespace()
# 6.np.random()
## arrays have some attributes and functions

In [2]:
import numpy as np

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.linspace(0,10,10,dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [9]:
list(range(1,11,1)) # always done in int

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
np.random.randint(1,6,1)

array([5])

In [14]:
np.random.randint(31,6000,[4,3])

array([[1977, 4746, 1672],
       [5925, 2077,  240],
       [4210, 5394, 1666],
       [3712,  287, 3354]])

In [17]:
np.random.seed(10)
np.random.randint(31,6000,[4,3],)

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [18]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [19]:
r =np.loadtxt('somedata.txt',dtype=str)
r

array(['this', 'is', 'python', 'file'], dtype='<U6')

In [20]:
r =np.loadtxt('moredata.txt')
r

array([[ 40.,  50.,  55.],
       [108., 204., 605.]])

In [21]:
p = np.random.rand(3,4)
p

array([[0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [23]:
np.savetxt('new.txt',p,delimiter=',')

In [ ]:
np.load